### ISSUE TITLE
Add a completed percentage

### ISSUE THREAD

**Issue by Maxzhao1999** [Sognus/EDMC-Autopath#2]
It would be a very nice feature to know what percentage of the distance and distance/total distance travelled!

**Comment by Sognus** [comment]
I have included information about route progress (completed, total, percentage) into version 1.1.0. It was added bellow clipboard update as text. Please respond if it need to be changed visually. 

As for distance traveled and total distance traveled. I haven't tested whether API is flexible enough to allow me to implement those yet. After some tests I will comment on this issue to let you know.

If there is anything else, please let me know.

**Comment by Maxzhao1999** [comment]
Thanks a lot for doing this! I'll take a look when I'm free. Amazing stuff!
