### ISSUE TITLE
Incompatible with "ED Recon (EDR)" EDMC plugin

### ISSUE THREAD

**Issue by Paspasote** [Sognus/EDMC-Autopath#5]
EDMC runs well with one of them (either edr or autopath) but It does not run with both installed.

**Comment by Sognus** [comment]
I have fixed an issue that blocked ED Recon from working together with EDMC Autopath. Fix was included into version 1.1.0. 

I am closing this issue because its resolved for me and for testers that helps me. If issue is not resolved for you let me know so I can reopen issue.
